import Head from "next/head";

export default function Index(){
    
    return(
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black h-screen text-white">
        <div className="text-center pt-10 text-7xl">

        platos tochkebii
        </div>
<div className="text-center mt-40 bg-[#f5ec42] text-black border border-white">plato mdebareobs ukiduresi varketilit. aq cxovroben shariani mastebi da zogjer ichitebian dedamotynulebic romlebsac shoridanve tasaobis manerit, andac saubris stilit daumugamebt.
aseti mastebis gatyvnistanave unda gaacno tavi da tu iazvobs deda unda moutynat. 
  
</div>
      </main>
    </>
  );
};
